train:
  _target_: src.datasets.WavDataset
  wav_dir: "/kaggle/input/ljspeechdatasethifigan/data/wavs"
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.WavDataset
  wav_dir: "/kaggle/input/validation/validation"
  instance_transforms: ${transforms.instance_transforms.train} 
