train:
  _target_: src.datasets.WavDataset
  wav_dir: "/Users/legend/Desktop/Универ/4/DLA/new_hw3/LJSpeech-1.1/wavs"
  limit: 2
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.WavDataset
  wav_dir: "/Users/legend/Desktop/Универ/4/DLA/new_hw3/validation"
  instance_transforms: ${transforms.instance_transforms.train} 
