train:
  - _target_: src.metrics.MOSMetric
    name: "MOSMetric" # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.MOSMetric
    name: "MOSMetric"
  # - _target_: src.metrics.ArgmaxWERMetric
  #   name: "WER_(Argmax)"
